name: 'Run submodule tests'
description: 'Runs make run-test and supplies all necessary files.'

runs:
  using: "composite"
  steps:
      - name: "Test Build"
        run: |
          echo "Test"
          chmod +x workflow-run.sh
          bash workflow-run.sh
