on: push

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test
        run: echo "Hey"
      - name: Test actions
        uses: Janmtbehrens/OpenSlides/dev/actions/build-and-test-service@main