on: push

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Prettify code
        uses: creyD/prettier_action@v4.6
        with:
          # This part is also where you can pass other options, for example:
          prettier_options: --check **/*.{sh}