on: deployment

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test actions
        uses: Janmtbehrens/OpenSlides/dev/actions/build-and-test-service@all-in-one
        with:
          service: auth