on: commit

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: Janmtbehrens/OpenSlides/dev/actions/branch-regex@reusable-github-actions
        with:
          regex: reusable-github-.*
        id: regex_match

      - name: Test branch
        if: ${{ steps.regex_match.outputs.match != '' }}
        run: echo "Branch worked"

      - name: Checks
        run: |
          echo "${{ steps.regex_match.outputs.match }}"
          echo "reusable-github-*"

      - uses: Janmtbehrens/OpenSlides/dev/actions/branch-regex@reusable-github-actions
        with:
          regex: .*
        id: regex_match2

      - name: Test branch
        if: ${{ steps.regex_match2.outputs.match != '' }}
        run: echo "Branch worked"

      - name: Checks
        run: |
          echo "${{ steps.regex_match2.outputs.match }}"
          echo "reusable-github-*"
      
      - uses: Janmtbehrens/OpenSlides/dev/actions/branch-regex@reusable-github-actions
        with:
          regex: reusable-github-actions
        id: regex_match3

      - name: Test branch
        if: ${{ steps.regex_match3.outputs.match != '' }}
        run: echo "Branch worked"

      - name: Checks
        run: |
          echo "${{ steps.regex_match3.outputs.match }}"
          echo "reusable-github-*"