on: push

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Workspace
        uses: ${{ github.workspace }}
      - name: Test actions
        uses: ./.github/actions/test-submodule