name: 'Issue Actions'

description: 'Various Issue related Actions'

on:
  workflow_call:
    inputs:
      action_type:
        description: Event Action Type that triggered this workflow
        required: true

jobs:
  project-automation-calls:
    runs-on: ubuntu-latest
    secrets: inherit
    steps:
      - name: Issue closed
        if: ${{ inputs.action_type == "closed" }}
        uses: Janmtbehrens/OpenSlides/dev/actions/project-automation@reusable-github-actions
        with:
          resource_node_id: ${{ github.event.issue.node_id }}
          status_value: "Done"
          gh_app_ID: ${{ secrets.AUTOMATION_APP_ID }}
          gh_app_installation_ID: ${{ secrets.AUTOMATION_APP_INSTALLATION_ID }}
          gh_app_secret_key: ${{ secrets.AUTOMATION_APP_PRIVATE_KEY }}

      
      - name: Issue opened
        if: ${{ inputs.action_type == "opened" || inputs.action_type == "reopened" }}
        uses: Janmtbehrens/OpenSlides/dev/actions/project-automation@reusable-github-actions
        with:
          resource_node_id: ${{ github.event.issue.node_id }}
          status_value: "Backlog"
          gh_app_ID: ${{ secrets.AUTOMATION_APP_ID }}
          gh_app_installation_ID: ${{ secrets.AUTOMATION_APP_INSTALLATION_ID }}
          gh_app_secret_key: ${{ secrets.AUTOMATION_APP_PRIVATE_KEY }}